### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by Bitart** [lucasvdh/laravelwhatsapp#1]

**Comment by Bitart** [comment]
Hi,
There has been a long time I am trying to find a reliable and stable solution to send and use, with responsability, messages with Whatsapp. Is this working?

**Comment by lucasvdh** [comment]
Hi, last time I checked, about 4 months ago, this code was still working.

However, Whatsapp frowns upon clients like these. If they find out that you are using an unofficial client they will permaban your phone number.

I would suggest waiting until Whatsapp supports official chat bots, but I'm not sure they ever will. Alternatively you could just use a messaging app that already supports these features like Telegram.

**Comment by Bitart** [comment]
Lucas,

Indeed. Unfortunatly there is a lot of persons around that does not give a...for responsability. But this package it would be enough to just send messages? I tried to set it up, with no success. So, I did not even receive authorization code.

Thanks for  your response.

Regards,
